export { getPool, closePool } from './pool.js';
export {
  createUser,
  getUserByUsername,
  getUserById,
  createLongLivedToken,
  getLongLivedTokenByUserId,
  getLongLivedTokenByHash,
  updateLongLivedToken,
  updateTokenLastUsed,
  getDiscordAccount,
  getDiscordAccountByDiscordId,
  saveDiscordAccount,
  updateRpcStatus,
  getUserSettings,
  updateUserSettings,
  createJwtSession,
  getJwtSession,
  deleteJwtSession,
  deleteAllJwtSessions,
  createClient,
  getClient,
  getClientsByUser,
  updateClientLastSeen,
  setClientConnected,
  deleteClient,
  deleteAllClients,
} from './queries.js';
export type {
  User,
  DiscordAccount,
  LongLivedToken,
  JwtSession,
  UserSettings,
  Client,
  DiscordData,
} from './queries.js';
